theme = "hugo-bootswatch"
baseURL = "https://vegawidget.netlify.com/"
languageCode = "en-us"
title = "vegawidget"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    dateFormat = "2006-01-02" 
 