theme = "hugo-bootswatch"
baseURL = "https://vegawidget.netlify.io/"
languageCode = "en-us"
title = "vegawidget"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

dateForm = "2006-01-02" 